### ISSUE TITLE
Cant figure out how to download belt Tension calculator 

### ISSUE THREAD

**Issue by KA009onPC** [bigtreetech/Belter-belt-tension-Tool#4]
Could you please send screen shots of how to install this please?

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. You just need to click the download button in this page 
https://github.com/bigtreetech/Belter-belt-tension-Tool/blob/master/Calculation%20Tool/Belter_tension_calculator.xlsx
Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
